/**
 * Type stub for the Remix server build.
 * The actual file is generated by `remix vite:build` into build/server/
 * This stub prevents TypeScript errors during development.
 */
declare module '../build/server' {
  export * from '@remix-run/cloudflare';
}
